services:
  node:
    build: 
      context: ..
      dockerfile: .docker/dockerfile
    image: node
    volumes:
      - ../:/workspace
    ports:
      - "3000:3000"
    working_dir: /workspace
    stdin_open: true
    tty: true
