services:
  postgres:
    container_name: postgreSQL
    image: postgres:17.2-alpine
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - ../data/postgres:/var/lib/postgresql/data
    networks:
      - postgres_network
    restart: unless-stopped

  pgadmin:
    container_name: pgAdmin
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    volumes:
      - ../data/pgadmin:/var/lib/pgadmin
      - ../data/queries:/var/lib/pgadmin/storage/admin_admin.com
    networks:
      - postgres_network
    depends_on:
      - postgres
    restart: unless-stopped

networks:
  postgres_network:
    driver: bridge

volumes:
  postgres:
  pgadmin:
