# subir o ambiente?
up:
	docker compose -f .docker/compose.yml up -d
	@echo "Ambiente subido com sucesso!"

# descer?
down:
	docker compose -f .docker/compose.yml down
	@echo "Ambiente parado com sucesso!"
